#! /usr/bin/env bash

root -b -l -q ComputeSignalLoss.cxx\(\"Xi\",kStandalone\)
root -b -l -q ComputeSignalLoss.cxx\(\"Xi\",kStandalone,1\)
root -b -l -q ComputeSignalLoss.cxx\(\"Xi\",kHighMult\)
root -b -l -q ComputeSignalLoss.cxx\(\"Xi\",kLowMult\)
root -b -l -q ComputeSignalLoss.cxx\(\"Xi\",kHighZN\)
root -b -l -q ComputeSignalLoss.cxx\(\"Xi\",kLowZN\)
root -b -l -q ComputeSignalLoss.cxx\(\"Lambda\",kStandalone\)
root -b -l -q ComputeSignalLoss.cxx\(\"Lambda\",kStandalone,1\)
root -b -l -q ComputeSignalLoss.cxx\(\"Lambda\",kHighMult\)
root -b -l -q ComputeSignalLoss.cxx\(\"Lambda\",kLowMult\)
root -b -l -q ComputeSignalLoss.cxx\(\"Lambda\",kHighZN\)
root -b -l -q ComputeSignalLoss.cxx\(\"Lambda\",kLowZN\)
root -b -l -q ComputeSignalLoss.cxx\(\"K0Short\",kStandalone\)
root -b -l -q ComputeSignalLoss.cxx\(\"K0Short\",kStandalone,1\)
root -b -l -q ComputeSignalLoss.cxx\(\"K0Short\",kHighMult\)
root -b -l -q ComputeSignalLoss.cxx\(\"K0Short\",kLowMult\)
root -b -l -q ComputeSignalLoss.cxx\(\"K0Short\",kHighZN\)
root -b -l -q ComputeSignalLoss.cxx\(\"K0Short\",kLowZN\)