#! /usr/bin/env bash

root -l -q -b DrawSpectra.cxx\(0,\"K0Short\"\)
root -l -q -b DrawSpectra.cxx\(1,\"K0Short\"\)
root -l -q -b DrawSpectra.cxx\(2,\"K0Short\"\)
root -l -q -b DrawSpectra.cxx\(3,\"K0Short\"\)
root -l -q -b DrawSpectra.cxx\(4,\"K0Short\"\)
root -l -q -b DrawSpectra.cxx\(0,\"Lambda\"\)
root -l -q -b DrawSpectra.cxx\(1,\"Lambda\"\)
root -l -q -b DrawSpectra.cxx\(2,\"Lambda\"\)
root -l -q -b DrawSpectra.cxx\(3,\"Lambda\"\)
root -l -q -b DrawSpectra.cxx\(4,\"Lambda\"\)
root -l -q -b DrawSpectra.cxx\(0,\"AntiLambda\"\)
root -l -q -b DrawSpectra.cxx\(1,\"AntiLambda\"\)
root -l -q -b DrawSpectra.cxx\(2,\"AntiLambda\"\)
root -l -q -b DrawSpectra.cxx\(3,\"AntiLambda\"\)
root -l -q -b DrawSpectra.cxx\(4,\"AntiLambda\"\)
root -l -q -b DrawSpectra.cxx\(0,\"XiMinus\"\)
root -l -q -b DrawSpectra.cxx\(1,\"XiMinus\"\)
root -l -q -b DrawSpectra.cxx\(2,\"XiMinus\"\)
root -l -q -b DrawSpectra.cxx\(3,\"XiMinus\"\)
root -l -q -b DrawSpectra.cxx\(4,\"XiMinus\"\)
root -l -q -b DrawSpectra.cxx\(0,\"XiPlus\"\)
root -l -q -b DrawSpectra.cxx\(1,\"XiPlus\"\)
root -l -q -b DrawSpectra.cxx\(2,\"XiPlus\"\)
root -l -q -b DrawSpectra.cxx\(3,\"XiPlus\"\)
root -l -q -b DrawSpectra.cxx\(4,\"XiPlus\"\)
